"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict
import apispec
from flask.app import Flask
from webargs.flaskparser import abort
from .spec import APISpecMixin
from .blueprint import Blueprint
from .pagination import Page
from .error_handler import ErrorHandlerMixin

"""Api extension initialization"""
__version__ = "0.25.0"


class Api(APISpecMixin, ErrorHandlerMixin):
    """Main class

    Provides helpers to build a REST API using Flask.

    :param Flask app: Flask application
    :param dict spec_kwargs: kwargs to pass to internal APISpec instance

    The ``spec_kwargs`` dictionary is passed as kwargs to the internal APISpec
    instance. **flask-smorest** adds a few parameters to the original
    parameters documented in :class:`apispec.APISpec <apispec.APISpec>`:

    :param apispec.BasePlugin flask_plugin: Flask plugin
    :param apispec.BasePlugin marshmallow_plugin: Marshmallow plugin
    :param list|tuple extra_plugins: List of additional ``BasePlugin``
        instances
    :param str title: API title. Can also be passed as
        application parameter `API_TITLE`.
    :param str version: API version. Can also be passed as
        application parameter `API_VERSION`.
    :param str openapi_version: OpenAPI version. Can also be passed as
        application parameter `OPENAPI_VERSION`.

    This allows the user to override default Flask and marshmallow plugins.

    For more flexibility, additional spec kwargs can also be passed as app
    parameter `API_SPEC_OPTIONS`.
    """

    spec: apispec.APISpec = ...

    def __init__(self, app=..., *, spec_kwargs: Dict[str, Any] = ...) -> None:
        ...

    def init_app(self, app: Flask, *, spec_kwargs: Dict[str, Any] = ...) -> None:
        """Initialize Api with application

        :param dict spec_kwargs: kwargs to pass to internal APISpec instance.
            Updates ``spec_kwargs`` passed in ``Api`` init.
        """
        ...

    def register_blueprint(self, blp: Blueprint, **options: Dict[str, Any]) -> None:
        """Register a blueprint in the application

        Also registers documentation for the blueprint/resource

        :param Blueprint blp: Blueprint to register
        :param dict options: Keyword arguments overriding Blueprint defaults

        Must be called after app is initialized.
        """
        ...
