"""
This type stub file was generated by pyright.
"""

import http
from typing import Any, Callable, Dict, Sequence, TypeVar, Union

from marshmallow.schema import Schema

RT = TypeVar("RT")

"""Response processor"""


class ResponseMixin:
    """Extend Blueprint to add response handling"""

    def response(
        self,
        schema: Schema = ...,
        *,
        code: Union[int, str, http.HTTPStatus] = ...,
        description: str = ...,
        example: Dict[Any, Any] = ...,
        examples: Sequence[Dict[Any, Any]] = ...,
        headers: Dict[str, Any] = ...
    ) -> Callable[[Callable[..., RT]], Callable[..., RT]]:
        """Decorator generating an endpoint response

        :param schema: :class:`Schema <marshmallow.Schema>` class or instance.
            If not None, will be used to serialize response data.
        :param int|str|HTTPStatus code: HTTP status code (default: 200).
            Used if none is returned from the view function.
        :param str description: Description of the response (default: None).
        :param dict example: Example of response message.
        :param list examples: Examples of response message.
        :param dict headers: Headers returned by the response.

        The decorated function is expected to return the same types of value
        than a typical flask view function, except the body part may be an
        object or a list of objects to serialize with the schema, rather than
        a ``string``.

        If the decorated function returns a ``Response`` object, the ``schema``
        and ``code`` parameters are only used to document the resource.

        The `example` and `examples` parameters are mutually exclusive. The
        latter should only be used with OpenAPI 3.

        The `example`, `examples` and `headers` parameters are only used to
        document the resource.

        See :doc:`Response <response>`.
        """
        ...
