"""
This type stub file was generated by pyright.
"""

"""Custom field properties functions"""
def uploadfield2properties(self, field, **kwargs):
    """Document Upload field properties in the API spec"""
    ...

