"""
This type stub file was generated by pyright.
"""

import sys

PY2 = sys.version_info[0] == 2
if PY2:
    def iteritems(d):
        ...
    
    def itervalues(d):
        ...
    
    xrange = xrange
    string_types = (unicode, bytes)
    def to_str(x, charset=..., errors=...):
        ...
    
else:
    def iteritems(d):
        ...
    
    def itervalues(d):
        ...
    
    xrange = range
    string_types = (str, )
    def to_str(x, charset=..., errors=...):
        ...
    
