"""
This type stub file was generated by pyright.
"""

class _Config(object):
    """
    Helper object for accessing and verifying options in this extension. This
    is meant for internal use of the application; modifying config options
    should be done with flasks ```app.config```.

    Default values for the configuration options are set in the jwt_manager
    object. All of these values are read only. This is simply a loose wrapper
    with some helper functionality for flasks `app.config`.
    """
    @property
    def is_asymmetric(self):
        ...
    
    @property
    def encode_key(self):
        ...
    
    @property
    def decode_key(self):
        ...
    
    @property
    def token_location(self):
        ...
    
    @property
    def jwt_in_cookies(self):
        ...
    
    @property
    def jwt_in_headers(self):
        ...
    
    @property
    def jwt_in_query_string(self):
        ...
    
    @property
    def jwt_in_json(self):
        ...
    
    @property
    def header_name(self):
        ...
    
    @property
    def header_type(self):
        ...
    
    @property
    def query_string_name(self):
        ...
    
    @property
    def access_cookie_name(self):
        ...
    
    @property
    def refresh_cookie_name(self):
        ...
    
    @property
    def access_cookie_path(self):
        ...
    
    @property
    def refresh_cookie_path(self):
        ...
    
    @property
    def cookie_secure(self):
        ...
    
    @property
    def cookie_domain(self):
        ...
    
    @property
    def session_cookie(self):
        ...
    
    @property
    def cookie_samesite(self):
        ...
    
    @property
    def json_key(self):
        ...
    
    @property
    def refresh_json_key(self):
        ...
    
    @property
    def csrf_protect(self):
        ...
    
    @property
    def csrf_request_methods(self):
        ...
    
    @property
    def csrf_in_cookies(self):
        ...
    
    @property
    def access_csrf_cookie_name(self):
        ...
    
    @property
    def refresh_csrf_cookie_name(self):
        ...
    
    @property
    def access_csrf_cookie_path(self):
        ...
    
    @property
    def refresh_csrf_cookie_path(self):
        ...
    
    @property
    def access_csrf_header_name(self):
        ...
    
    @property
    def refresh_csrf_header_name(self):
        ...
    
    @property
    def csrf_check_form(self):
        ...
    
    @property
    def access_csrf_field_name(self):
        ...
    
    @property
    def refresh_csrf_field_name(self):
        ...
    
    @property
    def access_expires(self):
        ...
    
    @property
    def refresh_expires(self):
        ...
    
    @property
    def algorithm(self):
        ...
    
    @property
    def decode_algorithms(self):
        ...
    
    @property
    def blacklist_enabled(self):
        ...
    
    @property
    def blacklist_checks(self):
        ...
    
    @property
    def blacklist_access_tokens(self):
        ...
    
    @property
    def blacklist_refresh_tokens(self):
        ...
    
    @property
    def cookie_max_age(self):
        ...
    
    @property
    def identity_claim_key(self):
        ...
    
    @property
    def user_claims_key(self):
        ...
    
    @property
    def user_claims_in_refresh_token(self):
        ...
    
    @property
    def exempt_methods(self):
        ...
    
    @property
    def error_msg_key(self):
        ...
    
    @property
    def json_encoder(self):
        ...
    
    @property
    def audience(self):
        ...
    
    @property
    def issuer(self):
        ...
    
    @property
    def leeway(self):
        ...
    


config = _Config()
